{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5ddfe7d7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🤖 Welcome to ChatBot! Type 'bye' anytime to exit.\n",
      "\n",
      "Before we start, may I know your name? Nikita\n",
      "Bot: Nice to meet you, Nikita! 👋 Type 'help' if you need options.\n",
      "\n",
      "Nikita: help\n",
      "Bot: You can ask me about time, date, weather, math, or even a joke!\n",
      "Nikita: joke\n",
      "Bot: Math fact: Zero is the only number that can’t be represented in Roman numerals.\n",
      "Nikita: math\n",
      "Bot: Hmm... I didn’t catch that. Type 'help' to see what I can do.\n",
      "Nikita: add\n",
      "Bot: The sum is 0\n",
      "Nikita: add 1 and 8\n",
      "Bot: The sum is 9\n",
      "Nikita: bye\n",
      "Bot: Bye Nikita! It was nice chatting with you. 👋\n",
      "Bot: Here’s what we talked about today:\n",
      "  1. help\n",
      "  2. joke\n",
      "  3. math\n",
      "  4. add\n",
      "  5. add 1 and 8\n",
      "  6. bye\n"
     ]
    }
   ],
   "source": [
    "import datetime\n",
    "import random\n",
    "\n",
    "print(\"🤖 Welcome to ChatBot! Type 'bye' anytime to exit.\\n\")\n",
    "\n",
    "user_name = input(\"Before we start, may I know your name? \")\n",
    "print(f\"Bot: Nice to meet you, {user_name}! 👋 Type 'help' if you need options.\\n\")\n",
    "\n",
    "\n",
    "chat_history = []\n",
    "\n",
    "\n",
    "jokes = [\n",
    "    \"Why don’t scientists trust atoms? Because they make up everything! 😆\",\n",
    "    \"Did you know? Python was named after 'Monty Python', not the snake! 🐍\",\n",
    "    \"Math fact: Zero is the only number that can’t be represented in Roman numerals.\"\n",
    "]\n",
    "\n",
    "while True:\n",
    "    user_input = input(f\"{user_name}: \").lower()\n",
    "    chat_history.append(user_input)\n",
    "\n",
    "    if any(greet in user_input for greet in [\"hi\", \"hello\", \"hey\"]):\n",
    "        print(f\"Bot: Hey {user_name}! How’s your day going?\")\n",
    "        \n",
    "    elif \"how are you\" in user_input:\n",
    "        print(\"Bot: I'm just code, but I'm functioning perfectly 😄 What about you?\")\n",
    "        \n",
    "    elif \"your name\" in user_input:\n",
    "        print(\"Bot: I'm RuleBot, your friendly rule-based chatbot 🤖\")\n",
    "\n",
    "    elif \"help\" in user_input:\n",
    "        print(\"Bot: You can ask me about time, date, weather, math, or even a joke!\")\n",
    "\n",
    "    elif \"time\" in user_input:\n",
    "        current_time = datetime.datetime.now().strftime(\"%I:%M %p\")\n",
    "        print(f\"Bot: The current time is {current_time}\")\n",
    "\n",
    "    elif \"date\" in user_input or \"day\" in user_input:\n",
    "        today = datetime.datetime.now().strftime(\"%A, %d %B %Y\")\n",
    "        print(f\"Bot: Today is {today}\")\n",
    "\n",
    "    elif \"weather\" in user_input:\n",
    "        print(\"Bot: I'm not connected to live weather data 🌦, but I hope it’s pleasant where you are!\")\n",
    "\n",
    "    elif \"joke\" in user_input or \"fact\" in user_input:\n",
    "        print(\"Bot:\", random.choice(jokes))\n",
    "\n",
    "    elif \"add\" in user_input or \"plus\" in user_input:\n",
    "        try:\n",
    "            numbers = [int(s) for s in user_input.split() if s.isdigit()]\n",
    "            print(f\"Bot: The sum is {sum(numbers)}\")\n",
    "        except:\n",
    "            print(\"Bot: Hmm, I couldn’t calculate that. Try like 'add 5 and 10'.\")\n",
    "    \n",
    "    elif \"bye\" in user_input:\n",
    "        print(f\"Bot: Bye {user_name}! It was nice chatting with you. 👋\")\n",
    "        print(\"Bot: Here’s what we talked about today:\")\n",
    "        for i, msg in enumerate(chat_history, 1):\n",
    "            print(f\"  {i}. {msg}\")\n",
    "        break\n",
    "\n",
    "    else:\n",
    "        print(\"Bot: Hmm... I didn’t catch that. Type 'help' to see what I can do.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3a419d0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
